2021-11-15 08:24:35,254 INFO <module> Tkinter version: 8.6
2021-11-15 08:24:35,254 DEBUG <module> All modules imported
2021-11-15 08:24:36,473 DEBUG __init__ Settings loaded
2021-11-15 08:24:36,540 DEBUG __init__ Icons loaded
2021-11-15 08:24:36,541 DEBUG __init__ Theme loaded
2021-11-15 08:24:36,568 DEBUG __initialize_custom_style Initialized custom style.
2021-11-15 08:24:55,644 DEBUG create_menu Right-click menu created
2021-11-15 08:24:55,674 DEBUG create_menu Menu created
2021-11-15 08:24:55,674 DEBUG create_bindings Bindings created
2021-11-15 08:24:55,679 DEBUG start_screen Start screen created
2021-11-15 08:24:55,947 DEBUG update_title update_title: No file open
2021-11-15 08:24:55,947 DEBUG update_statusbar update_statusbar: No file open
2021-11-15 08:24:58,530 DEBUG update_statusbar update_statusbar: No file open
2021-11-15 08:24:58,530 DEBUG update_title update_title: No file open
2021-11-15 08:24:58,530 DEBUG mouse update_title: OK
2021-11-15 08:24:58,597 ERROR open_file Error when opening file:
Traceback (most recent call last):
  File "/home/runner/PyPlus/Mac/src/editor.py", line 493, in open_file
    if is_binary_string(open(file, "rb").read()):
IsADirectoryError: [Errno 21] Is a directory: '/home/runner/PyPlus/Mac/src/Settings'
2021-11-15 08:24:58,662 DEBUG update_statusbar update_statusbar: No file open
2021-11-15 08:24:58,662 DEBUG update_title update_title: No file open
2021-11-15 08:24:58,662 DEBUG mouse update_title: OK
2021-11-15 08:24:59,618 DEBUG update_statusbar update_statusbar: No file open
2021-11-15 08:24:59,618 DEBUG update_title update_title: No file open
2021-11-15 08:24:59,618 DEBUG mouse update_title: OK
2021-11-15 08:25:00,003 ERROR open_file Error when opening file:
Traceback (most recent call last):
  File "/home/runner/PyPlus/Mac/src/editor.py", line 493, in open_file
    if is_binary_string(open(file, "rb").read()):
IsADirectoryError: [Errno 21] Is a directory: '/home/runner/PyPlus/Mac/src/Settings/a'
2021-11-15 08:25:00,085 DEBUG update_statusbar update_statusbar: No file open
2021-11-15 08:25:00,085 DEBUG update_title update_title: No file open
2021-11-15 08:25:00,085 DEBUG mouse update_title: OK
2021-11-15 08:25:06,910 DEBUG create_text_widget Textbox created
2021-11-15 08:25:06,924 DEBUG update_statusbar update_statusbar: OK
2021-11-15 08:25:06,924 DEBUG update_title update_title: OK
2021-11-15 08:25:06,924 DEBUG mouse update_title: OK
2021-11-15 08:25:06,925 INFO open_file File opened
2021-11-15 08:25:08,513 DEBUG update_statusbar update_statusbar: OK
2021-11-15 08:25:08,513 DEBUG update_title update_title: OK
2021-11-15 08:25:08,514 DEBUG mouse update_title: OK
2021-11-15 08:25:08,601 ERROR open_file Error when opening file:
Traceback (most recent call last):
  File "/home/runner/PyPlus/Mac/src/editor.py", line 493, in open_file
    if is_binary_string(open(file, "rb").read()):
IsADirectoryError: [Errno 21] Is a directory: '/home/runner/PyPlus/Mac/src/Settings'
2021-11-15 08:25:08,698 DEBUG update_statusbar update_statusbar: OK
2021-11-15 08:25:08,698 DEBUG update_title update_title: OK
2021-11-15 08:25:08,698 DEBUG mouse update_title: OK
2021-11-15 08:25:09,479 DEBUG update_statusbar update_statusbar: OK
2021-11-15 08:25:09,480 DEBUG update_title update_title: OK
2021-11-15 08:25:09,480 DEBUG mouse update_title: OK
2021-11-15 08:25:09,550 ERROR open_file Error when opening file:
Traceback (most recent call last):
  File "/home/runner/PyPlus/Mac/src/editor.py", line 493, in open_file
    if is_binary_string(open(file, "rb").read()):
IsADirectoryError: [Errno 21] Is a directory: '/home/runner/PyPlus/Mac/src/Settings/a'
2021-11-15 08:25:09,630 DEBUG update_statusbar update_statusbar: OK
2021-11-15 08:25:09,630 DEBUG update_title update_title: OK
2021-11-15 08:25:09,630 DEBUG mouse update_title: OK
2021-11-15 08:25:10,813 DEBUG update_statusbar update_statusbar: OK
2021-11-15 08:25:10,813 DEBUG update_title update_title: OK
2021-11-15 08:25:10,813 DEBUG mouse update_title: OK
